### ISSUE TITLE
NextCloud 11.0.1 Error

### ISSUE THREAD

**Issue by MathiasRenner** [guillaumev/owncloud_for_filelink#47]
When trying to setup the connection up in Thunderbird (45.5.1), it says something like **An Error ocurred** without more Details.

Looking at the webserver's log where the nextcloud resides, it shows: 
```
Code 412:    Method: POST   //ocs/v1.php/person/check?format=json
```

Other clients show this log entry when they succeed:
```
Code: 200    Method: GET    /ocs/v2.php/apps/notifications/api/v2/notifications
```
Note the difference in the initial `//` of the path and the versin of the API (`v1` vs. `v2`)

Can this be fixed by deleting the `/` here?
https://github.com/guillaumev/owncloud_for_filelink/blob/master/components/nsOwncloud.js#L22

**Comment by dom-madrid** [comment]
Just updated from NextCloud 10 to 11 on Ubuntu 16.04 server. Running TB 45.7 on Ubuntu 16.04 desktop. What used to work, no longer works. The Secure access did no longer work on the existing install, so I removed the xpi, reinstalled it and I can no longer setup a server. Same error message as reported earlier. 
On the server side:
errors that appeared when trying to connect:
Error	OCP\AppFramework\QueryException: Could not resolve OCA\Richdocuments\Settings\Section! Class OCA\Richdocuments\Settings\Section does not exist	2017-02-10T19:20:48+0100
Debug	CSRF check failed	2017-02-10T19:20:41+0100

**Comment by ArnY** [comment]
There's a new mandatory http header to access nextcloud 11 API:

OCS-APIREQUEST: true

the nsOwncloud.js component needs to be updated.

**Comment by guillaumev** [comment]
This should now be fixed. 1.4 release is on its way.

**Comment by MathiasRenner** [comment]
I am sorry, it's still not working for me. I can set the account up in Thunderbird and it's logs into my nextcloud when clicking on `authorize` in the according menu setting. Everything OK here.

But when I wanna write an email and upload the attachment, it says `Unable to upload test.jpg to ownCloud/nextCloud.`

I haven't checked the logs of my Nextcloud instance yet.

**Comment by guillaumev** [comment]
Which exact version of nextcloud are you using ?

**Comment by MathiasRenner** [comment]
Latest, `11.0.2 `

**Comment by guillaumev** [comment]
I just double checked by upgrading my nextcloud instance to 11.0.2 (was running 11.0.1) and it still works fine. Can you double check that the storage folder, if you configured one, does exist in your nextcloud instance ? Also, are you protecting files with a password ?

**Comment by MathiasRenner** [comment]
Now it says `An unknown error occurred when communicating with ownCloud/nextCloud.` I changed the following:

- I changed the storage folder to `/`
- I didn't configure a password in the filelink plugin
- In my nextcloud settings, `Allow users to share via link` is activated, and password encr. is not enforced
- The nextcloud instance works fine for the sync client (mobile and dekstop) 
- The file in the email is actually uploaded correctly to the Nextcloud! But the link to the cloud is not inserted.
- During the upload of the file, the apache log says twice this error: `GET /index.php/login?redirect_url=/ocs/v1.php/apps/files_sharing/api/v1/shares%3Fformat%3Djson HTTP/1.1`

Hope that helps.

**Comment by guillaumev** [comment]
Could you send me the URL of your nextcloud instance and a user/password I could try with ? Send it as private message obviously.

**Comment by MathiasRenner** [comment]
I just sent you an email.

**Comment by c4539** [comment]
Hi,
hope you are well.
I get the same error message in Thunderbird when uploading files to my Nextcloud 11.0.2.7 using the "Nextcloud for Filelink" AddOn 1.5.
The upload itself finishes successfully, but sharing fails.
The Apache access log tells me the sharing request is not authorized (HTTP 401):
"POST /ocs/v1.php/apps/files_sharing/api/v1/shares?format=json HTTP/1.1" 401
I'm experiencing this error with the TOTP active as well as inactive.
Any further ideas?
Simon
